# Generated by Django 5.2 on 2025-04-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_cliente_delete_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='preco',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='servico',
            field=models.CharField(choices=[('Corte de cabelo', 'Corte de cabelo'), ('Manicure', 'Manicure'), ('Hidratação', 'Hidratação'), ('Escova', 'Escova'), ('Coloração', 'Coloração'), ('Design de sobrancelha', 'Design de sobrancelha'), ('Depilação', 'Depilação'), ('Pedicure', 'Pedicure'), ('Progressiva', 'Progressiva'), ('Maquiagem', 'Maquiagem'), ('Corte infantil', 'Corte infantil'), ('Penteado', 'Penteado')], max_length=50),
        ),
    ]
