# Generated by Django 5.2 on 2025-04-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_cliente_preco_alter_cliente_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='servico',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='horario',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='cliente',
            name='servicos',
            field=models.ManyToManyField(to='agendamentos.servico'),
        ),
    ]
